services:
  manager:
    build : .
    #variables d'environnement pour les fichiers python
    environment:
      CSV_FILENAME : data.csv
      POSTGRES_USER : user #doit etre pareil que dans l'environnement de db. Du coup si on spécifie pas le POSTGRES_USER dans l'environnement de db, il faudra marquer "root" à la place "user"
      POSTGRES_PASSWORD : pwd #doit etre pareil que dans l'environnement de db
      POSTGRES_DB : database #doit etre pareil que dans l'environnement de db. Du coup si on spécifie pas le POSTGRES_DB dans l'environnement de db, il faudra marquer la valeur de POSTGRES_USER à la place "database"
    depends_on:
      - db

  db:
    image : postgres
    restart: always
    #variables d'environnement pour initialiser la db
    environment:
      POSTGRES_USER : user #facultatif. Si pas spécifié, par défaut le user est "root"
      POSTGRES_PASSWORD : pwd #obligatoire
      POSTGRES_DB : database #facultatif. Si pas spécifié, par défaut la database s'appelle pareil que POSTGRES_USER

