services:
  manager:
    build : .
    environment:
      CSV_FILENAME : data.csv
      POSTGRES_PASSWORD : root
      POSTGRES_USER : root
      POSTGRES_DB : database
    depends_on:
      - db

  db:
    image : postgres
    restart: always
    environment:
      CSV_FILENAME : data.csv
      POSTGRES_PASSWORD : root
      POSTGRES_USER : root
      POSTGRES_DB : database

